<a href="https://colab.research.google.com/github/eliteprashanna07-lab/mathematics/blob/main/Workshop6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* ** Prashanna Khanal**
* *University ID =2401205*

In [2]:
#EX1
import numpy as np

if __name__ == '__main__':
  arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype= float)
print("Array =")
print(arr)
print("Data Type of the Array = ", arr.dtype)
print("Number of dimentions of the Array= " , arr.ndim)
print("Shape of the array =", arr.shape)
print("Size of the array =", arr.size)
print("Number of bytes used by each element of the array=", arr.itemsize)
print("Total bytes used by the Array=", arr.nbytes)
print("Memory layout information =", arr.flags)

Array =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Data Type of the Array =  float64
Number of dimentions of the Array=  2
Shape of the array = (3, 3)
Size of the array = 9
Number of bytes used by each element of the array= 8
Total bytes used by the Array= 72
Memory layout information =   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [4]:
#Ex2
arr2 = 3 * np.ones((4,5), dtype=float)
print("Array =")
print(arr2)
print("Shape=",arr2.shape)
print("DataType" , arr2.dtype)

Array =
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape= (4, 5)
DataType float64


In [5]:
#Ex3
arr4 = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
print("Array =")
print(arr4)
print("Shape=",arr4.shape)
print("DataType" , arr4.dtype)

Array =
[[0 1 2]
 [1 2 3]
 [2 3 4]]
Shape= (3, 3)
DataType int64


In [9]:
def dot_product(vec1, vec2):
  vec1= vec1.flatten()
  vec2= vec2.flatten()
  return np.sum(np.multiply(vec1, vec2))

def matrix_vector_product(mat, vec):
  m,n= mat.shape
  p,q=vec.shape

  assert n==p, "the matrix and vectors are not compatible for multiplication!"

  result = np.zeros((m,q), dtype=float)
  for i in range(m):
    result[i] = dot_product(mat[i,:], vec)
    return result
if __name__ =="__main__":

  mat1 = np.full((3,3),3,dtype=int)
  vec1 =np.full((3,1),2,dtype=int)
  print("Matrix= ")
  print(mat1)
  print("Vector= ")
  print(vec1)
  print("Result=")
  result1= matrix_vector_product(mat1, vec1)
  print(result1)

  result2= mat1@vec1
  print("Result=")
  print(result2)

Matrix= 
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector= 
[[2]
 [2]
 [2]]
Result=
[[18.]
 [ 0.]
 [ 0.]]
Result=
[[18]
 [18]
 [18]]


In [10]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(arr@arr2)

[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]


In [13]:
def check_symmetric(arr1):
  arr2=arr1.transpose()
  return np.array_equal(arr1,arr2)
arr1= np.array([[0,1,2],[1,0,3],[2,3,0]])
print(check_symmetric(arr1))

True
